image: docker:latest
services:
- name: docker:dind
  alias: docker

stages:
- info
- build
- test

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: registry.gitlab.com/siimeon/dockercomposegitlabci:$CI_COMMIT_REF_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

docker-info:
  stage: info
  script:
    - docker info

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

docker-compose-version:
  stage: test
  script:
    - docker pull $CONTAINER_IMAGE
    - docker run $CONTAINER_IMAGE docker-compose --version
