image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

stages:
- build
- test

build:
  stage: build
  before_script:
  - docker info
  script:
  - docker build -t dockercomposegitlabci .
  - docker ps -a

test:
  stage: test
  script:
  - docker run dockercomposegitlabci docker-compose --version
