name: Dockerhub build
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
            push: true
            tags: shaakana/dockercomposegitlabci:withAwsTools20-10
            platforms: linux/amd64,linux/arm64
